a = float(input("Enter first number:"))
b = float(input("Enter second number:"))
print("Before swapping the values of a and b are ", a,"and", b)
(a,b)=(b,a)
print("After swapping the values of a and b are ", a,"and", b)